name: WilliamNS

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stabshubhamxddle-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/Kucingnakal160/rdpgratis1/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Kucingnakal160/rdpgratis1/main/wallpaper.png -OutFile wallpaper.png
        Invoke-WebRequest https://raw.githubusercontent.com/Kucingnakal160/rdpgratis1/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Kucingnakal160/rdpgratis1/main/loop.bat -OutFile loop.bat
    - name: Download Launcher
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/Kucingnakal160/rdpgratis1/main/launcher/Node.js.lnk -OutFile Node.js.lnk
        Invoke-WebRequest https://raw.githubusercontent.com/Kucingnakal160/rdpgratis1/main/launcher/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"
    - name: Extracting Ngrok Files
